apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: loki
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.7.4
        command:
          - -config.file=/etc/loki/local-config.yaml
        ports:
        - containerPort: 3100
        envFrom:
          - configMapRef:
              name: loki-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  selector:
    app: loki # label selectors Pod loki
  ports:
    - port: 3100 # port of the serivce
      targetPort: 3100 # port of the container that service will forward to