apiVersion: apps/v1
kind: Deployment
metadata:
  name: latipe-rating-service
spec:
  replicas: 1
  strategy: # change here
    type: RollingUpdate # strategy type is Recreate or RollingUpdate. Default is RollingUpdate
  selector:
    matchLabels:
      app: latipe-rating-service
  template:
    metadata:
      labels:
        app: latipe-rating-service
    spec:
      containers:
        - image: 0353486363/latipe-rating-service:latest
          imagePullPolicy: IfNotPresent
          name: latipe-rating-service
          env:
            - name: SETTINGS_FILE
              value: "k8s.json"
          resources:
            requests:
              cpu: 200m
      # restartPolicy: Always


---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: latipe-rating-service
spec:
  scaleTargetRef:
    apiVersion: apps/v2
    kind: Deployment
    name: latipe-rating-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
