apiVersion: apps/v1
kind: Deployment
metadata:
  name: latipe-cart-service
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy: # change here
    type: RollingUpdate # strategy type is Recreate or RollingUpdate. Default is RollingUpdate
  selector:
    matchLabels:
      app: latipe-cart-service
  template:
    metadata:
      labels:
        app: latipe-cart-service
    spec:
      containers:
        - image: 0353486363/latipe-cart-service:97d6b7b
          imagePullPolicy: IfNotPresent
          name: latipe-cart-service
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: latipe-service-secret
                  key: SPRING_DATA_MONGODB_URI
          envFrom:
            - configMapRef:
                name: latipe-service-configmap
          resources:
            limits:
              cpu: 700m
              memory: 700Mi
            requests:
              cpu: 200m
              memory: 300Mi
      restartPolicy: Always
