apiVersion: v1
kind: ConfigMap
metadata:
  name: latipe-api-gateway-service-configmap
data:
  GATEWAY_ROUTES: /conf/latipe-api-gateway-service/gateway.yaml
  gateway.yaml: |-
    routes:
    - id: auth_service
      paths:
        - /api/v1/auth/**
      filter:
        requestRateLimiter:
          replenishRate: 1000
          burstCapacity: 10000
          requestedTokens: 10
        responseHeaders:
          - Access-Control-Allow-Origin: "*"
          - Access-Control-Allow-Methods: "*"
          - Access-Control-Allow-Headers: "*"
          - Access-Control-Max-Age: "30"
      uri: latipe-auth-service.latipe.svc.cluster.local:8081
    - id: user_service
      paths:
        - /api/v1/users/**
        - /api/v1/tokens/**
      filter:
        requestRateLimiter:
          replenishRate: 1000
          burstCapacity: 10000
          requestedTokens: 10
        responseHeaders:
          - Access-Control-Allow-Origin: "*"
          - Access-Control-Allow-Methods: "*"
          - Access-Control-Allow-Headers: "*"
          - Access-Control-Max-Age: "30"
      uri: latipe-user-service.latipe.svc.cluster.local:8888
    - id: cart_service
      paths:
        - /api/v1/carts/**
      filter:
        requestRateLimiter:
          replenishRate: 1000
          burstCapacity: 10000
          requestedTokens: 10
        responseHeaders:
          - Access-Control-Allow-Origin: "*"
          - Access-Control-Allow-Methods: "*"
          - Access-Control-Allow-Headers: "*"
          - Access-Control-Max-Age: "30"
      uri: latipe-cart-service.latipe.svc.cluster.local:7650
    - id: media_service
      paths:
        - /api/v1/medias/**
      filter:
        requestRateLimiter:
          replenishRate: 1000
          burstCapacity: 10000
          requestedTokens: 10
      uri: latipe-media-service.latipe.svc.cluster.local:7657
    - id: product_service
      paths:
        - /api/v1/products/**
        - /api/v1/categories/**
      filter:
        requestRateLimiter:
          replenishRate: 1000
          burstCapacity: 10000
          requestedTokens: 10
        responseHeaders:
          - Access-Control-Allow-Origin: "*"
          - Access-Control-Allow-Methods: "*"
          - Access-Control-Allow-Headers: "*"
          - Access-Control-Max-Age: "30"
      uri: latipe-product-service.latipe.svc.cluster.local:8645
    - id: search_service
      paths:
        - /api/v1/search/**
      filter:
        requestRateLimiter:
          replenishRate: 1000
          burstCapacity: 10000
          requestedTokens: 10
        responseHeaders:
          - Access-Control-Allow-Origin: "*"
          - Access-Control-Allow-Methods: "*"
          - Access-Control-Allow-Headers: "*"
          - Access-Control-Max-Age: "30"
      uri: latipe-search-service.latipe.svc.cluster.local:8092
    - id: store_service
      paths:
        - /api/v1/stores/**
        - /api/v1/commissions/**
      filter:
        requestRateLimiter:
          replenishRate: 1000
          burstCapacity: 10000
          requestedTokens: 10
        responseHeaders:
          - Access-Control-Allow-Origin: "*"
          - Access-Control-Allow-Methods: "*"
          - Access-Control-Allow-Headers: "*"
          - Access-Control-Max-Age: "30"
      uri: latipe-store-service.latipe.svc.cluster.local:8118
    - id: payment_service
      paths:
        - /api/v1/payment/**
        - /api/v1/payment-providers/**
      filter:
        requestRateLimiter:
          replenishRate: 1000
          burstCapacity: 10000
          requestedTokens: 10
        responseHeaders:
          - Access-Control-Allow-Origin: "*"
          - Access-Control-Allow-Methods: "*"
          - Access-Control-Allow-Headers: "*"
          - Access-Control-Max-Age: "30"
      uri: latipe-payment-service.latipe.svc.cluster.local:8381
    - id: rating_service
      paths:
        - /api/v1/ratings/**
      filter:
        requestRateLimiter:
          replenishRate: 1000
          burstCapacity: 10000
          requestedTokens: 10
        responseHeaders:
          - Access-Control-Allow-Origin: "*"
          - Access-Control-Allow-Methods: "*"
          - Access-Control-Allow-Headers: "*"
          - Access-Control-Max-Age: "30"
      uri: latipe-rating-service.latipe.svc.cluster.local:8777
    - id: orders_service
      paths:
        - /api/v1/orders/**
        - /api/v2/orders/**
      filter:
        responseHeaders:
          - Access-Control-Allow-Origin: "*"
          - Access-Control-Allow-Methods: "*"
          - Access-Control-Allow-Headers: "*"
          - Access-Control-Max-Age: "30"
      uri: http://localhost:5000
    - id: delivery_service
      paths:
        - /api/v1/delivery/**
      uri: http://localhost:5005
    - id: vouchers_service
      paths:
        - /api/v1/vouchers/**
      filter:
        responseHeaders:
          - Access-Control-Allow-Origin: "*"
          - Access-Control-Allow-Methods: "*"
          - Access-Control-Allow-Headers: "*"
          - Access-Control-Max-Age: "30"
      uri: http://localhost:5010
