apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
    - type: Container
      default: # this section defines default limits
        cpu: 200m
        memory: 300Mi
      defaultRequest: # this section defines default requests
        cpu: 200m
        memory: 300Mi
      min:
        cpu: 100m
      max:
        cpu: 2000m
        memory: 4Gi
